<?php $status = $this->getStatus(); ?>
<li class="clean_or_dirty">
    <?php if (false === $status->isDirty()): ?>
    <?php echo $this->__("Workspace is clean"); ?>
    <?php else: ?>
    <?php echo $this->__("Workspace is dirty"); ?>
    <?php endif; ?>
</li>
<?php if (0 < count($status->getChangedFiles())): ?>
<li class="changed_files">
    <?php echo $this->__("Changed files: ");?>
    <ul>
        <?php foreach ($status->getChangedFiles() as $file): ?>
        <li><?php echo $file; ?></li>
        <?php endforeach; ?>
    </ul>
</li>
<?php endif; ?>
<?php if (0 < count($status->getUntrackedFiles()) && $this->showUntracked()): ?>
<li class="untracked_files">
    <?php echo $this->__("Untracked files: ");?>
    <ul>
        <?php foreach ($status->getUntrackedFiles() as $file): ?>
        <li><?php echo $file; ?></li>
        <?php endforeach; ?>
    </ul>
</li>
<?php endif; ?>


