<?php if ($this->getIncludeUpdater()):?>
<div id="gitInfo">
<?php endif; ?>
    <div class="git_informations">
        <ul class="branch"><?php echo $this->getChildHtml('magegitinfo_branch') ?></ul>
        <ul class="status"><?php echo $this->getChildHtml('magegitinfo_status') ?></ul>
        <ul class="log"><?php echo $this->getChildHtml('magegitinfo_log') ?></ul>
    </div>
<?php if ($this->getIncludeUpdater()): ?>
</div>
<script type="text/javascript">
<!--
    new Ajax.PeriodicalUpdater({success: 'gitInfo'}, '<?php echo $this->getUpdaterUrl(); ?>',{
        method: 'post',
        evalScripts: true,
        frequency: <?php echo $this->getUpdaterFrequency(); ?>,
        parameters: {'isAjax': true},
        loaderArea: false,
    });
//-->
</script>
<?php endif; ?>